name: Github Pages deployment
on:
  push:
    branches:
      - main
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  build-and-deploy:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.11

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm install

      - name: Build
        working-directory: ./docs
        run: pnpm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        working-directory: ./docs
        with:
          branch: gh-pages
          folder: dist
